const GALLERY_IMAGES = [
  { src: 'images/Raised_Deck_Main.jpg', alt: 'Custom raised deck railing with metal balusters', category: 'railings', title: 'Raised Deck Railing' },
  { src: 'images/Ramp_Railing_Main.jpg', alt: 'Accessible ramp railing installation', category: 'railings', title: 'Ramp Railing' },
  { src: 'images/Kitchen_Railing_Main.jpg', alt: 'Interior kitchen railing with custom metalwork', category: 'railings', title: 'Kitchen Railing' },
  { src: 'images/Outdoor_Railing_Main.jpg', alt: 'Outdoor deck railing with artistic metal design', category: 'railings', title: 'Outdoor Railing' },
  { src: 'images/Outdoor_Roof_Main.jpg', alt: 'Rooftop patio railing with mountain views', category: 'railings', title: 'Rooftop Patio Railing' },
  { src: 'images/wire_Railing_Main.jpg', alt: 'Modern wire cable railing system', category: 'railings', title: 'Wire Cable Railing' },
  { src: 'images/Outdoor_Patio_Main.jpg', alt: 'Custom patio railing overlooking Colorado landscape', category: 'railings', title: 'Patio Railing' },
  { src: 'images/Outdoor_Deck_Main.jpg', alt: 'Outdoor deck with custom metal railing', category: 'railings', title: 'Outdoor Deck Railing' },
  { src: 'images/Inside_Out_Main.jpg', alt: 'Indoor-outdoor railing connecting living spaces', category: 'railings', title: 'Indoor-Outdoor Railing' },
  { src: 'images/MultiLevel_Main.jpg', alt: 'Multi-level deck railing system', category: 'railings', title: 'Multi-Level Railing' },
  { src: 'images/Mountain_House_Main.jpg', alt: 'Mountain home custom railing installation', category: 'railings', title: 'Mountain Home Railing' },
  { src: 'images/MH6.jpg', alt: 'Mountain house deck railing detail', category: 'railings', title: 'Mountain House Detail' },
  { src: 'images/Modern%20_City_Main.jpg', alt: 'Modern urban home metal railing', category: 'railings', title: 'Modern City Railing' },
  { src: 'images/MC2.jpg', alt: 'Contemporary metal railing design', category: 'railings', title: 'Contemporary Railing' },
  { src: 'images/MC5.jpg', alt: 'Custom metal railing with clean lines', category: 'railings', title: 'Custom Metal Railing' },
  { src: 'images/MC6.jpg', alt: 'Modern residential railing installation', category: 'railings', title: 'Modern Residential Railing' },
  { src: 'images/MC10.jpg', alt: 'Artistic metal railing for city home', category: 'railings', title: 'Artistic City Railing' },
  { src: 'images/Commercial_Main.jpg', alt: 'Professional metal railing for residential property', category: 'railings', title: 'Residential Railing' },
  { src: 'images/Grand_Staircase_Main.jpg', alt: 'Grand staircase with custom metal railing', category: 'stairs', title: 'Grand Staircase' },
  { src: 'images/Stairs%20%26%20Landings%20Main.jpg', alt: 'Custom stairs and landing with metal railing', category: 'stairs', title: 'Stairs & Landings' },
  { src: 'images/Multi_Staircase_Main.jpg', alt: 'Multi-level staircase with artistic railing', category: 'stairs', title: 'Multi-Level Staircase' },
  { src: 'images/Full_Stair_Rail_Main.jpg', alt: 'Full stair railing from top to bottom', category: 'stairs', title: 'Full Stair Railing' },
  { src: 'images/Full_Stair_Rail_2_Main.jpg', alt: 'Complete stair railing installation', category: 'stairs', title: 'Complete Stair Railing' },
  { src: 'images/Front_Steps_Main.jpg', alt: 'Front entrance steps with custom railing', category: 'stairs', title: 'Front Steps' },
  { src: 'images/Spiral_Stairs.jpg', alt: 'Spiral staircase with custom metalwork', category: 'stairs', title: 'Spiral Stairs' },
  { src: 'images/Landing.jpg', alt: 'Stair landing with decorative metal railing', category: 'stairs', title: 'Stair Landing' },
  { src: 'images/Treads.jpg', alt: 'Custom metal stair treads', category: 'stairs', title: 'Custom Stair Treads' },
  { src: 'images/SH3.jpg', alt: 'Staircase detail with expert craftsmanship', category: 'stairs', title: 'Staircase Detail' },
  { src: 'images/Stairs_Railig_Main.jpg', alt: 'Stair railing with artistic metal design', category: 'stairs', title: 'Stair Railing' },
  { src: 'images/Stairs_Walkway_Main.jpg', alt: 'Exterior stair walkway with railing', category: 'stairs', title: 'Stair Walkway' },
  { src: 'images/Basement_Entrance_Main.jpg', alt: 'Basement entrance stairs with railing', category: 'stairs', title: 'Basement Entrance' },
  { src: 'images/Fence2.jpg', alt: 'Custom metal fence for residential property', category: 'gates-fences', title: 'Custom Metal Fence' },
  { src: 'images/Fence3_2.jpg', alt: 'Decorative metal fence installation', category: 'gates-fences', title: 'Decorative Fence' },
  { src: 'images/Door2_1.jpg', alt: 'Custom metal door with artistic design', category: 'doors', title: 'Custom Metal Door' },
  { src: 'images/Door3.jpg', alt: 'Unique metal door fabrication', category: 'doors', title: 'Unique Metal Door' },
  { src: 'images/GarbageDoor_1.jpg', alt: 'Custom metal enclosure door', category: 'doors', title: 'Custom Enclosure Door' },
  { src: 'images/WindowCover3_1.jpg', alt: 'Custom metal window cover', category: 'window-covers', title: 'Window Cover' },
  { src: 'images/WindowCover_5.jpg', alt: 'Decorative metal window cover installation', category: 'window-covers', title: 'Decorative Window Cover' }
];